### ISSUE TITLE
AccessTokenテーブルの簡略化

### ISSUE THREAD

**Issue by yagi2** [geckour/Egret#3]
大してMastodonのAPIまだ見てないけど過去のAccessTokenって保存する必要なさそう（こなみ）
isCurrentカラムを削除して、insert or updateでいい感じに1つの要素だけを持ったほうが良さそう。
アホみたいにリログしまくってるとDBで容量圧迫されるかも。

**Comment by geckour** [comment]
複数インスタンスにログインしたいユーザーみたいなのがいた時、切り替えるたびにログイン要求したらうざいかなーと思ったんだよね。
僕もあんまりちゃんとAPI見てないからなんとも言えないけど

**Comment by yagi2** [comment]
あ〜〜〜なるほどな〜〜。
それなら仕方ないな……。 複数インスタンス切り替えられてなんぼみたいなところはあるしな……。
Twitterクライアント作るときは複垢に悩まされ、ますとどんでは複インスタンスに悩まされるのか……。

**Comment by geckour** [comment]
とりあえずこの実装で進めますか

**Comment by yagi2** [comment]
おけい👍
閉じとく！
