### ISSUE TITLE
ブランチの運用をどうするか

### ISSUE THREAD

**Issue by geckour** [geckour/Egret#4]
Git flow？
それともGitHub flow？

**Comment by yagi2** [comment]
ライトな感じでいいと思われ〜。
個人的によく使うのはmixしてるやつで

- master -> 安定版リリースブランチ
- develop -> 開発版リリースブランチ
- feature/hoge -> 機能追加

が主かもしれない。
運用的には
- feature/hoge で機能追加等を行う
- developにマージ（この時PRを出すか出さないかはお好み）
- developが安定して動いて、それなりに機能が追加されたらmasterにマージ
- masterにマージしたらバージョンのタグ付け e.g 1.0.0

な感じ。
好きなようにやるのがいいかもしれぬ。

**Comment by geckour** [comment]
ありがとう。
じゃあ合わせますー
