### ISSUE TITLE
Toot内のアカウントへのリンクをタップした際にアプリ内でプロフィールビューを表示する

### ISSUE THREAD

**Issue by geckour** [geckour/Egret#49]
現状すべてのリンクがChromeに投げられているので、アプリ内で対応可能な内容はアプリ側で処理する

**Comment by yagi2** [comment]
SpannableStringを使うと思うけど、せっかくならhttpな外部サイトへのリンクはChrome Custom Tabsを使ったほうがユーザーフレンドリーかもしれない（たぶん）（僕はそっちのがこのみ）

**Comment by geckour** [comment]
僕はChromeで開いてくれる方が好きなので、設定で切り替えられるようにしよう

**Comment by yagi2** [comment]
低メモリだとChromeアプリが起動した時にIntent発行元のアプリが死ぬことがあるからそういう意味でもオススメ感はある。

**Comment by geckour** [comment]
デフォはカスタムタブで設定でアプリと切り替え可能ってのがいい線だろうか

**Comment by yagi2** [comment]
のがいいかもしれん。 僕は割とWebに飛ばすときはカスタムタブで実装してChromeで開きたいときはChromeで開くを使うみたいな運用でカバーをしてる。
自分がChromeで開いてくれるのが好きなら切り替え可能がよさそう。

**Comment by geckour** [comment]
APIの仕様的に、in reply toなアカウントのID(1アカウントのみ)しか取れないので、厳しみにあふれている。
よってプロフィールビューを開くのは諦めるが、カスタムタブの実装は進める。

**Comment by geckour** [comment]
カスタムタブとChromeアプリの切り替え機能実装完了
