### ISSUE TITLE
RecyclerViewにデータを追加してもViewがバインドされない

### ISSUE THREAD

**Issue by geckour** [geckour/Egret#5]
Adapterが持つArrayListには追加されるものの、onCreateViewHolderが呼ばれてないっぽい。
当然ViewHolderは作られずonBindViewHolderも呼ばれない。

**Comment by yagi2** [comment]
RecyclerView、heightもwidthも0dpになってるやで……

**Comment by geckour** [comment]
ﾜｧｵｰ Constraint Layoutの頃の名残かな（）

**Comment by geckour** [comment]
直してくれたので閉じます
