### ISSUE TITLE
主にストリーム系のコネクションを適切に管理する

### ISSUE THREAD

**Issue by geckour** [geckour/Egret#50]
現状はコネクションを開いたら開きっぱなしで画面遷移しようが何の処理も入れていないので、適切なタイミングで切断/再接続する

**Comment by geckour** [comment]
関連して、全ての通信がタイムアウトしないようになっているので、ストリーム系とその他でタイムアウト時間を分ける

**Comment by yagi2** [comment]
RxJavaで通信だよね。だったらonPauseとかでdisposeとかかな (コネクション系の切断）

**Comment by geckour** [comment]
そんな感じやねー

**Comment by geckour** [comment]
ストリーム系については切断の実装を完了、タイムアウト時間の設定も完了
