### ISSUE TITLE
Streamingのドメインが違う場合のリクエスト

### ISSUE THREAD

**Issue by yagi2** [geckour/Egret#8]
Mastodonは設定ファイルでstreaming apiのホストを変えることができるのでそれの対処が必要そう。

mstdn.jp は mstdn.jp/api/v1 (301) -> streaming.mstdn.jp にリダイレクトされる。
現状だとリダイレクトされる際にリクエストヘッダーが無いので401（UnAuthorization)になってるのでそこをいい感じに直したい。

**Comment by geckour** [comment]
あれリダイレクトの結果だったのか。てっきり各インスタンスごとに手動で設定必要かと思ってました
リダイレクト時もヘッダつける方法ですなー

**Comment by geckour** [comment]
解決！
